vich_uploader:
    db_driver: orm
    metadata: 
        type: attribute

    mappings:
        cars:
            uri_prefix: '%car_images%'
            upload_destination: '%kernel.project_dir%/public/images/cars'
            delete_on_remove: true
